[package]
name = "owner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "main_2"
path = "src/main_2.rs"
[[bin]]
name = "main_3"
path = "src/main_3.rs"

[dependencies]
