[package]
name = "generic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "trait"
path = "src/trait.rs"

[[bin]]
name = "lifetime"
path = "src/lifetime.rs"

[dependencies]
